### ISSUE TITLE
Stuck in loop while connecting

### ISSUE THREAD

**Issue by mattncsu** [thingsboard/thingsboard-python-client-sdk#5]
For a while my code to post to thingsboard will work normally and then suddenly, the code will enter a loop where it repeatedly says connection SUCCESS every few ms until I terminate the script:

```
2020-05-15 23:51:31,012 -  INFO - connection SUCCESS
2020-05-15 23:51:31,016 -  INFO - connection SUCCESS
2020-05-15 23:51:31,877 -  INFO - connection SUCCESS
2020-05-15 23:51:31,897 -  INFO - connection SUCCESS
2020-05-15 23:51:31,939 -  INFO - connection SUCCESS
2020-05-15 23:51:31,945 -  INFO - connection SUCCESS
2020-05-15 23:51:31,953 -  INFO - connection SUCCESS
2020-05-15 23:51:31,973 -  INFO - connection SUCCESS
2020-05-15 23:51:32,010 -  INFO - connection SUCCESS
2020-05-15 23:51:32,016 -  INFO - connection SUCCESS
2020-05-15 23:51:32,022 -  INFO - connection SUCCESS
^CException ignored in: <module 'threading' from '/usr/lib/python3.7/threading.py'>
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 1281, in _shutdown
    t.join()
  File "/usr/lib/python3.7/threading.py", line 1032, in join
    self._wait_for_tstate_lock()
  File "/usr/lib/python3.7/threading.py", line 1048, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt
```
Here is how I'm using it:
```
from pyvesync_v2 import VeSync
import time
from time import localtime, strftime
#import os, sys, platform, datetime
import requests
from tb_device_mqtt import TBDeviceMqttClient, TBPublishInfo

TB_Token = "xxx"

manager = VeSync("email", "password", time_zone="America/New York")
manager.login()

# Get/Update Devices from server - populate device lists
manager.update()

my_switch = manager.outlets[0]

# Get energy usage data
manager.energy_update_interval = 3 * 60
manager.update()

# Display outlet device information
for device in manager.outlets:
    device.display()

while True:
    manager.update()
    print(strftime("%a, %d %b %Y %H:%M:%S",localtime()))
    print("%5.2fW - active for %d" %(manager.outlets[1].power,manager.outlets[1].active_time))
    if manager.outlets[1].power > 0.0:
        telemetry = {"power": manager.outlets[1].power}
        client = TBDeviceMqttClient("192.168.1.100", TB_Token)
        # Connect to ThingsBoard
        client.connect()
        # Sending telemetry without checking the delivery status
        client.send_telemetry(telemetry)
        # Sending telemetry and checking the delivery status (QoS = 1 by default)
        result = client.send_telemetry(telemetry)
        # get is a blocking call that awaits delivery status
        success = result.get() == TBPublishInfo.TB_ERR_SUCCESS
        # Disconnect from ThingsBoard
        client.disconnect()

    else:
        print("0.0W returned, possible API error.")
    time.sleep(manager.energy_update_interval)

```
Any thoughts on what I'm doing wrong?

**Comment by zbeacon** [comment]
Hi @mattncsu ,

It looks like you try to connect/disconnect on every time, when manager.outlets[1].power > 0.0.

It is bad decision because connection require some time and it works wrong. TBDeviceMqttClient already contains inside reconnection logic, so you are able to connect once and send data.

In your case code will look like:

```
from pyvesync_v2 import VeSync
import time
from time import localtime, strftime
#import os, sys, platform, datetime
import requests
from tb_device_mqtt import TBDeviceMqttClient, TBPublishInfo

TB_Token = "xxx"

manager = VeSync("email", "password", time_zone="America/New York")
manager.login()

# Get/Update Devices from server - populate device lists
manager.update()

my_switch = manager.outlets[0]

# Get energy usage data
manager.energy_update_interval = 3 * 60
manager.update()

# Display outlet device information
for device in manager.outlets:
    device.display()

client = TBDeviceMqttClient("192.168.1.100", TB_Token)
# Connect to ThingsBoard
client.connect()

while True:
    try:
        manager.update()
        print(strftime("%a, %d %b %Y %H:%M:%S",localtime()))
        print("%5.2fW - active for %d" %(manager.outlets[1].power,manager.outlets[1].active_time))
        if manager.outlets[1].power > 0.0:
            telemetry = {"power": manager.outlets[1].power}
            # Sending telemetry and checking the delivery status (QoS = 1 by default)
            result = client.send_telemetry(telemetry)
            # get is a blocking call that awaits delivery status
            success = result.get() == TBPublishInfo.TB_ERR_SUCCESS
        else:
            print("0.0W returned, possible API error.")
        time.sleep(manager.energy_update_interval)
    except Exception:
        client.disconnect()


```
