### ISSUE TITLE
AttributeError: 'TBGatewayMqttClient' object has no attribute '_add_timeout'

### ISSUE THREAD

**Issue by MohamedKHALILRouissi** [thingsboard/thingsboard-python-client-sdk#75]
Waiting for connection to be established before sending data to ThingsBoard!
Traceback (most recent call last):
  File "/home/khalil/test/gateway/tb_mqtt_sdk/test.py", line 13, in <module>
    gateway.gw_request_shared_attributes("SN-001", ["ruleChain"], callback)
  File "/home/khalil/test/gateway/tb_mqtt_sdk/tb_gateway_mqtt.py", line 191, in gw_request_shared_attributes
    return self.__request_attributes(device_name, keys, callback, False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/khalil/test/gateway/tb_mqtt_sdk/tb_gateway_mqtt.py", line 173, in __request_attributes
    self._add_timeout(attr_request_number, ts_in_millis + 30000)
    ^^^^^^^^^^^^^^^^^
AttributeError: 'TBGatewayMqttClient' object has no attribute '_add_timeout'

**Comment by MohamedKHALILRouissi** [comment]
this also fail at the thingsboard-gateway with mqtt connector requesting device attribtue
